### ISSUE TITLE
[BUG] presence or absence of conjunction

### ISSUE THREAD

**Issue by astefano** [konnov/apalache#133]
**Describe the bug**
Without a conjunction in front of line 146 (the line with: `AtLeastT2(msgsNewleaderForCurrView)`)  in the attached file (hotstuff_3phases_v0_no_conjunction.tla) Apalache returns the error in the error file.

**To Reproduce**
 - The command-line parameters that you use to run the tool
`docker run --rm -v /home/lacra/Downloads:/var/apalache apalache/mc check --inv=P5 hotstuff_3phases_v0.tla`
 - The problematic specification (if this cannot be submitted, try to come up with a minimal working example)
[hotstuff_3phases_v0_no_conjunction.zip](https://github.com/konnov/apalache/files/4508096/hotstuff_3phases_v0_no_conjunction.zip)

**Expected behavior**
What did you expect to see?
I was expecting that the presence of the conjunction should not have matter. 

**Log files**
If possible, submit `detailed.log` and the tool output.
[error_conjunction.txt](https://github.com/konnov/apalache/files/4508097/error_conjunction.txt)

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux (18.04 bionic)
- Java version:
java version "1.8.0_212"
Java(TM) SE Runtime Environment (build 1.8.0_212-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.212-b10, mixed mode)

**Comment by Kukovec** [comment]
Thanks for your report! The behavior you have observed is actually not a bug, but a consequence of how TLA+ handles "lists" of conjunctions/disjunctions. In essence, the placement of implicit parenthesis is different when one uses `/\` as "bullet-points", i.e. when every conjunct, including the first, is preceded by a conjunction symbol, and when one doesn't. For more details on how whitespace and leading conjunction affects the formula, I'd advise reading Lamport's "Specifying Systems" (p26 & p276).

In your particular case, because the leading conjunction is missing, the subformula 
```
/\ \A m \in msgsNewleaderForCurrView : ValidNewLeader(m)
/\ \E m1 \in msgsNewleaderForCurrView : ...
```
is parsed as 
```
/\ (\A m \in msgsNewleaderForCurrView : (
	ValidNewLeader(m)
	/\ \E m1 \in msgsNewleaderForCurrView : ... ))
```
instead of 
```
/\ (\A m \in msgsNewleaderForCurrView : ValidNewLeader(m) )
/\ (\E m1 \in msgsNewleaderForCurrView : ... )
```
which I assume you had expected.

This matters, because in the first case, most of the body of the formula falls under the quantifier `\A m \in msgsNewleaderForCurrView: ...`. Our assignment finder will not look for assignments inside universally quantified formulas (intuitively, one cannot simultaneously assign every value from a set to a variable), which is why an `AssignmentException` is produced, since it fails to find assignments within `OnNewleader(_)`.

To get the expected behavior, either use a leading conjunction or manually add parenthesis as below:
```
/\ (\A m \in msgsNewleaderForCurrView : ValidNewLeader(m) )
```

To avoid confusion in the future, I recommend adopting Lamport's bullet-point style (i.e. using leading conjunction/disjunction symbols) as that style's implicit parenthesis seem to correspond best to people's intuition.

**Comment by astefano** [comment]
Thank you very much for the clarification!
